### ISSUE TITLE
SET TIMEZONE support

### ISSUE THREAD

**Issue by shimizukawa** [shimizukawa/django-redshift-backend#10]
django-redshift-backend 0.5 disables SET TIMEZONE because old version of Redshift didn't support it. 

Now Redshift supports timezone since version 1.0.1103 (2016-09-30).
https://aws.amazon.com/jp/about-aws/whats-new/2016/09/amazon-redshift-introduces-new-data-type-to-support-time-zones-in-time-stamps/

Note that, It's dependent on the environment whether timezone feature can be used. Therefore we should consider there are environments which can't be used the feature.

refs:
- timestamptz explanation in Japanese: http://dev.classmethod.jp/cloud/aws/amazon-redshift-new-data-type-timestamptz/

**Comment by dkarchmer** [comment]
Is there a way to workaround in this for now? Is there any class I can overwrite to begin using timestamptz?

**Comment by emyller** [comment]
By using Django's `DateTimeField` in a RDBMS known to support time zones, one expects that it defaults to use it. In order to provide support for those who have been using time zone naive datetimes, I think we could:

1. Offer a `REDSHIFT_FORCE_NAIVE_DATETIME` -- or something like that -- to keep aliasing `DateTimeField` to `timestamp without time zone`.
2. Default all current values to UTC, unless the above is set.

**Comment by emyller** [comment]
BTW, there is a PR for that at https://github.com/shimizukawa/django-redshift-backend/pull/23.

**Comment by shimizukawa** [comment]
Now #23 has been merged!

**Comment by shimizukawa** [comment]
> `REDSHIFT_FORCE_NAIVE_DATETIME`

I studied about that idea, it is likely to become a debt in the long run, so it is not currently implemented. The version is less than 1.0, and I feel that I would like to lower long-term development and maintenance costs.

**Comment by emyller** [comment]
@shimizukawa As Redshift now has full timezone support, I believe there's no reason not to use it by default. And if someone really doesn't want that, they can tweak Django's `USE_TZ` accordingly.

Good point about the version < 1.0.0. Makes things simpler.
