### ISSUE TITLE
SELECT DISTINCT ON is not supported

### ISSUE THREAD

**Issue by jredd** [shimizukawa/django-redshift-backend#14]
In one of my views I need to call distinct on my query but I'm receiving this when I hit the django end point

```
Exception Type:	NotSupportedError
Exception Value:  SELECT DISTINCT ON is not supported
```

**Comment by arpitremarkable** [comment]
It is not supported by redshift itself, maybe you can use DISTINCT with a nested query to achieve what you want.

**Comment by emyller** [comment]
This doesn't seem to be an issue with django-redshift-backend and it's also not viable -- or even possible -- to interpret `distinct on` into `distinct` + subquery. 😞

**Comment by shimizukawa** [comment]
postgres backend on Django supports "SELECT DISTINCT ON" and other backends don't.
- https://github.com/django/django/blob/1.9/django/db/backends/base/operations.py#L130
- https://docs.djangoproject.com/en/dev/ref/models/querysets/#distinct

I couldn't find information that "DISTINCT ON" is not supported, but it seems that it doesn't actually support it.
http://docs.aws.amazon.com/redshift/latest/dg/c_unsupported-postgresql-features.html

For this reason I will explicitly implement unsupported with django redshift backend.

**Comment by GnanaShekhar** [comment]
> It is not supported by redshift itself, maybe you can use DISTINCT with a nested query to achieve what you want.

No its possible for multiple columns.

**Comment by jredd** [comment]
I could have sworn that distinct was possible...

https://docs.aws.amazon.com/redshift/latest/dg/r_DISTINCT_examples.html
