### ISSUE TITLE
Error on Travis CI

### ISSUE THREAD

**Issue by shimizukawa** [shimizukawa/django-redshift-backend#34]
### Problem
- Travis CI cause errors

#### Procedure to reproduce the problem
```
tox
```

#### Error logs / results
```
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```
- https://travis-ci.org/shimizukawa/django-redshift-backend/builds/365118759

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version: 3.5.5
- Django version: 1.8

**Comment by m-vdb** [comment]
Already fixed in this PR: https://github.com/shimizukawa/django-redshift-backend/pull/29/files#diff-46ee651bfd5c248d45fe4b9857abaf12R26

**Comment by shimizukawa** [comment]
I see, thanks for telling me.
As I review #29, it seems it will take time to merge.

**Comment by shimizukawa** [comment]
#36 fixes this.
